version: '3.6'
services:
  mariadb:
    build: ./mariadb
    volumes:
    - ./../Database/patches:/docker-entrypoint-initdb.d
    ports:
    - '3306:3306'
    environment:
    - MYSQL_USER=mysql
    - MYSQL_PASSWORD=vagrant
    - MYSQL_ROOT_PASSWORD=vagrant
  postfix:
    build: ./postfix
    ports:
    - '25:25'
    environment:
    - SMTP_SERVER=smtp.gmail.com
    - SMTP_USERNAME=jaylappdev@gmail.com
    - SMTP_PASSWORD=jaylapp123
    - SERVER_HOSTNAME=jaylapp.dev
    - SMTP_NETWORKS=127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
