[package]
name = "sample_endpoint"
version = "0.1.0"
authors = ["Tom Dymel <tom@dymel.dev>"]
edition = "2018"

[dependencies]
rocket = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["json"]