on:
  pull_request:
  push:
    branches:
      - master
      - "releases/*"

jobs:
  tests:
    name: "Integration testing"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Set up environment"
        run: docker compose -f docker-compose.yml up -d --wait
      - name: "Wait for docker to finish building"
      - name: "Test server"
        run: docker exec -it legacyplayersv4_webclient_1 echo "Test" > /var/www/test.html 
